### ISSUE TITLE
CRUD usuarios del sistema.

### ISSUE THREAD

**Issue by norcasitas** [Tec-Pro/Tik#2]
Se deberá realizar alta baja modificación y lectura del modulo usuario, el cual contendrá los siguientes datos:

 `name` 
`surname` 
`pass` 
`entry_date`
`exit_date` 
`turn` 
`date_of_birth`
`place_of_birth` 
`id_type` 
`id_number` 
`address`
`home_phone` 
`emergency_phone`
`mobile_phone` 
`marital_status` 
`blood_type` 

se deberá modificar la base de datos para agregar un campo "posición" así se le asignará : 
mozo/cocina/barra y poder saber en que se desempeña para generar su login correspondiente

SE DEBE REALIZAR ABM, INTERFAZ GRAFICA Y CONTROLADOR DE USUARIOS, 
 las implementaciones de los crud van en server, los controladores e interfaz en adminTik

**Comment by norcasitas** [comment]
@ezensich

**Comment by norcasitas** [comment]
Esto es para @MaxCej  y @agusbauer

**Comment by MaxCej** [comment]
Rev = 5b60d33
-Modifique la tabla users para agregarle el campo "position".
-Implemente el crudUser

**Comment by MaxCej** [comment]
Rev = c88e285
-Modifique el CrudUser
-Agregue la GuiCRUDUser
Nota:
- Falta agregar la incriptacion al CrudUser para la pass
- Falta agregar la tabla modelo para la tabla de la Gui
- Falta subir el controlador que aun no esta terminado

**Comment by MaxCej** [comment]
Rev = 1305f3f
-Agregue controlador para GuiCRUDUser
-Modifique la GuiCRUDUser, CrudUser y Interfacesde CrudUser
nota:
- Falta agregar 2 funcionalidades al controlador (borrar y modificar)

**Comment by MaxCej** [comment]
Rev = fdee96b
-Anda todo menos 1 cosa. Te podrias limpiar el culo con lo lindo que anda.
-Problemas desencryptando la contrasena. Me dice error de longitud.
