### ISSUE TITLE
CRUD ADMIN

### ISSUE THREAD

**Issue by norcasitas** [Tec-Pro/Tik#3]
Se deberá realizar alta, baja, modificación y lectura del modulo admin, el cual contendrá:
 `name` 
`pass` 

se deberá implementar abm, controlador, e interfaz grafica del modulo admin. 

abm va en SERVERTIK
controlador e interfaz va en ADMINTIK

**Comment by norcasitas** [comment]
@MaxCej

**Comment by agusbauer** [comment]
Primero hay que borrar todos los administradores de la base de datos que esten cargados de otra forma,  asi se crea automaticamente el administrador por defecto admin-admin. Con los administradores cargados de otra forma va a decir que las contraseñas no concuerdan por la encriptacion.

**Comment by norcasitas** [comment]
@agusbauer LA base de datos se debe abrir CADA vez que se acceda a ella, en los métodos de la implementación de interfaces, ergo error en el método dminExists(String name) (linea 32 de CrudAdmin)

**Comment by norcasitas** [comment]
Perdón, está todo bien. No vi que era privado y se invocaba más abajo con la base ya abierta.

**Comment by norcasitas** [comment]
Detalles a corregir para mejorar la interacción del usuario:

-Al abrir la ventana, que aparezca en el centro de la ventana, esto se logra seteando relativeLocation(null) o algo así antes de hacerla visible

-Jugar con los botones habilitados o no,es decir, al entrar a la configuración del admin, que tenga el textField de contraseña
y nombre bloqueado, cuando se ponga nuevo o modificar se habilite, y funciona perfecto al poner modificar un usuario o poner crear y luego sin guardar poner borrar.

-eliminar la posibilidad de que la ventana se agrande (se agranda y se desconfigura toda la parte visual) mejor si queda fija, es decir
que no sea resizable ni maximizable.

Lo demás funciona perfecto, incluso cuando se borran todos los usuarios, se cierra sesión y se crea nuevamente el admin, detalle perfecto!

-si es posible, estaría bueno usar keyReleased en la ventana login, para ingresar usuario, apretar enter y bajar al campo contraseña, ingresarla, apretar enter y bajar a ingresar o que ingrese con el ultimo enter de la contraseña
