### ISSUE TITLE
CRUD PROVEEDORES

### ISSUE THREAD

**Issue by norcasitas** [Tec-Pro/Tik#5]
Se deberá implementar el alta, baja y modificación de proveedores, y alta baja y modificacion de categorias (de proveedores)

Un proveedor tiene muchas categorias, una categoria tiene muchos proveedores (relacion n..n)

Un proveedor tiene : 
`name` 
`cuit` 
`address` 
`description`
`phones` 

La categoria: 
`name` 

Tambien se debe renombrar las tablas, para evitar problemas con ActiveJDBC, en lo posible evitar nombres con _ (guiones). Las relaciones entre proveedores se guardan en una tabla aparte.

La implementación e interfaz va en el proyecto server, en los correspondientes package, la interfaz gui y controladores va en el proyecto adminTik.

**Comment by norcasitas** [comment]
@ezensich

**Comment by jheredia** [comment]
@norcasitas aparentemente cambiarme de país me cagó el servidor, lo puedo hacer andar pero el cliente no se conecta con la siguiente excepción:
Exception in thread "main" java.security.AccessControlException: access denied ("java.net.SocketPermission" "192.168.0.79:1099" "connect,resolve")

Hasta donde había probado, los CRUD andaban.

**Comment by ezensich** [comment]
@jheredia Usa localhost tanto en server como en cliente, revisa que el puerto este abierto y que tengas los permisos en el java.policy, eso es lo unico que puede generar errores.

**Comment by jheredia** [comment]
No lo quiero cerrar porque anda pero se que se puede pulir un montón.
